version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net
  broker:
    image: confluentinc/cp-kafka:7.4.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - kafka-net
  payments-be:
    container_name: payments-be
    build: .
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    expose:
      - 8089
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongo_db:$MONGODB_DOCKER_PORT/$MONGODB_DATABASE?authSource=admin"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "broker:9092"
    networks:
      - kafka-net
  mongo_db:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    networks:
      - kafka-net

volumes:
  db:
networks:
  kafka-net:
    driver: bridge




#networks:
#  kafka-net:
#    external:
#      name: booking_kafka-net


#
#version: "3.8"
#services:
#
#  java:
#    build:
#      context: ./
#    ports:
#      - "8087:8088"
#    container_name: payments-be
#    links:
#      - mongo
#    depends_on:
#      - mongo
#    networks:
#      - shared-net
#
#  mongo:
#    image: 'mongo:latest'
#    ports:
#      - 27017:27017
#    container_name: booking-mongo_db-2
#    volumes:
#      - /home/sinoed/data/db:/data/db
#    networks:
#      - shared-net
#
#networks:
#  shared-net:
#    driver: bridge