apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-be
  template:
    metadata:
      labels:
        app: admin-be
    spec:
      containers:
      - name: admin-be
        image: ghcr.io/bogdanxu/admin:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://admin-postgres-service:5432/postgres"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "secret"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-broker-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-be-service
spec:
  selector:
    app: admin-be
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
