apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator-mongo-db
  template:
    metadata:
      labels:
        app: operator-mongo-db
    spec:
      containers:
      - name: operator-mongo-db
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "123456"

---
apiVersion: v1
kind: Service
metadata:
  name: operator-mongo-db-service
spec:
  selector:
    app: operator-mongo-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
