version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-net
  broker:
    image: confluentinc/cp-kafka:7.4.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - kafka-net   
  booking-be:
    container_name: booking-be
    depends_on:
      - mongo_db
      - broker
    build:
      context: ../booking
      dockerfile: Dockerfile
    ports:
      - 8181:8080
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.data.mongodb.uri" : "mongodb://root:123456@mongo_db:27017/booking_db?authSource=admin",
          "spring.kafka.bootstrap-servers": "broker:9092",
          "keycloak.auth-server-url": "http://keycloak:8080",
          "spring.security.oauth2.resourceserver.jwt.issuer-uri": "http://keycloak:8080/realms/auth_service",
          "app.jwks.uri": "http://keycloak:8080/realms/auth_service/protocol/openid-connect/certs"
        }'
    volumes:
      - booking-db:/data/db
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - kafka-net
  mongo_db:
    image: mongo:latest
    restart: unless-stopped
    env_file: ../booking/.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 7017:27017
    volumes:
      - mongo-db:/data/db
    networks:
      - kafka-net
  admin-postgres:
    image: postgres
    container_name: admin-postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - admin-postgres-data:/var/lib/postgresql/data
    ports:
      - 5435:5432
    expose:
      - 5435
    networks:
      - kafka-net
  admin-be:
    container_name: admin-be
    build:
      context: ../admin
      dockerfile: Dockerfile
    depends_on:
      - admin-postgres
      - broker
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://admin-postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "broker:9092"
    links:
      - admin-postgres
    networks:
      - kafka-net
  payments-be:
    container_name: payments-be
    build:
      context: ../payments
      dockerfile: Dockerfile
    depends_on:
      - payments-mongo_db
      - broker
    ports:
      - 8089:8080
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://root:123456@mongo_db:27017/booking_db?authSource=admin"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "broker:9092"
    volumes:
      - payments-db:/data/db
    networks:
      - kafka-net
  payments-mongo_db:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 7018:27017
    volumes:
      - payments-db:/data/db
    networks:
      - kafka-net
  operator-mongo_db:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 7019:27017
    volumes:
      - operator-db:/data/db
    networks:
      - kafka-net
  flight-search-be:
    container_name: flight-search-be
    build:
      context: ../flight-search
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - kafka-net
  notifications-be:
    container_name: notifications-be
    build:
      context: ../notification
      dockerfile: Dockerfile
    depends_on:
      - es01
    ports:
      - 8090:8084
    environment:
      - SPRING_ELASTICSEARCH_URIS= es01:9200
      - SPRING_KAFKA_BOOTSTRAP_SERVERS= broker:9092
    volumes:
      - payments-db:/data/db
    networks:
      - kafka-net
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.20
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - 5601:5601
    depends_on:
      - es01
    networks:
      - kafka-net
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.20
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - network.host= 0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - kafka-net
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.20
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - kafka-net
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.20
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
    - kafka-net
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak_v1
      KC_DB_PASSWORD: root
      KC_DB_USERNAME: postgres
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_JDBC_PARAMS: 'sslmode=require'
    ports:
      - "9090:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      kafka-net:
  keycloak-db:
    image: postgres:10
    command: ["postgres", "-c", "max_connections=200", "-c", "shared_buffers=24MB", "-c", "listen_addresses=*"]
    environment:
      POSTGRES_DB: keycloak_v1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    healthcheck:
      test: "exit 0"
    ports:
      - "5436:5432"
    networks:
      kafka-net:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    user: postgres
  keycloak-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "root"
    volumes:
      - redis_data:/data
  operator-be-lufthansa:
    container_name: operator-be-lufthansa
    build:
      context: ../operator
      dockerfile: Dockerfile
    depends_on:
      - operator-mongo_db
    ports:
      - "8282:8282"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://root:123456@operator-mongo_db:27017/operator_db?authSource=admin"
      airline.iata.code: LH
    volumes:
      - operator-db:/data/db
    networks:
      - kafka-net
  operator-be-tarom:
    container_name: operator-be-tarom
    build:
      context: ../operator
      dockerfile: Dockerfile
    depends_on:
      - operator-mongo_db
    ports:
      - "8383:8282"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://root:123456@operator-mongo_db:27017/operator_db?authSource=admin"
      airline.iata.code: RO
    volumes:
      - operator-db:/data/db
    networks:
      - kafka-net
  operator-be-wizz-air:
    container_name: operator-be-wizz-air
    build:
      context: ../operator
      dockerfile: Dockerfile
    depends_on:
      - operator-mongo_db
    ports:
      - "8384:8282"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://root:123456@operator-mongo_db:27017/operator_db?authSource=admin"
      airline.iata.code: WZ
    volumes:
      - operator-db:/data/db
    networks:
      - kafka-net
  operator-be-ryan-air:
    container_name: operator-be-ryan-air
    build:
      context: ../operator
      dockerfile: Dockerfile
    depends_on:
      - operator-mongo_db
    ports:
      - "8385:8282"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://root:123456@operator-mongo_db:27017/operator_db?authSource=admin"
      airline.iata.code: RY
    volumes:
      - operator-db:/data/db
    networks:
      - kafka-net
  operator-be-delta:
    container_name: operator-be-delta
    build:
      context: ../operator
      dockerfile: Dockerfile
    depends_on:
      - operator-mongo_db
    ports:
      - "8386:8282"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://root:123456@operator-mongo_db:27017/operator_db?authSource=admin"
      airline.iata.code: DT
    volumes:
      - operator-db:/data/db
    networks:
      - kafka-net
  operator-be-klm:
    container_name: operator-be-klm
    build:
      context: ../operator
      dockerfile: Dockerfile
    depends_on:
      - operator-mongo_db
    ports:
      - "8387:8282"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://root:123456@operator-mongo_db:27017/operator_db?authSource=admin"
      airline.iata.code: KM
    volumes:
      - operator-db:/data/db
    networks:
      - kafka-net
  operator-be-al-italia:
    container_name: operator-be-al-italia
    build:
      context: ../operator
      dockerfile: Dockerfile
    depends_on:
      - operator-mongo_db
    ports:
      - "8388:8282"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://root:123456@operator-mongo_db:27017/operator_db?authSource=admin"
      airline.iata.code: IT
    volumes:
      - operator-db:/data/db
    networks:
      - kafka-net
  operator-be-easy-jet:
    container_name: operator-be-easy-jet
    build:
      context: ../operator
      dockerfile: Dockerfile
    depends_on:
      - operator-mongo_db
    ports:
      - "8389:8282"
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://root:123456@operator-mongo_db:27017/operator_db?authSource=admin"
      airline.iata.code: EJ
    volumes:
      - operator-db:/data/db
    networks:
      - kafka-net
volumes:
  booking-db:
  mongo-db:
  admin-postgres-data:
  payments-db:
  operator-db:
  operator-vol-postgres:
  data01:
  data02:
  data03:
  postgres_data:
  redis_data:
networks:
  kafka-net:
    driver: bridge
  host:
    driver: bridge