version: '3.9'
services:
  db:
    image: postgres
    container_name: Admin_DB
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5435:5432
    expose:
      - 5435

