version: '3.9'
services:
  operator-postgres:
    container_name: operator-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - operator-vol-postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - host
  operator-be-lufthansa:
    container_name: operator-be-lufthansa
    build:
      context: .
    ports:
      - "8282:8282"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://operator-postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      airline.flight.code: LH
    links:
      - operator-postgres
    networks:
      - host

  operator-be-tarom:
    container_name: operator-be-tarom
    build:
      context: .
    ports:
      - "8383:8282"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://operator-postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      airline.flight.code: RO
    links:
      - operator-postgres
    networks:
      - host
volumes:
  operator-vol-postgres:
    driver: local
networks:
  host:
    driver: bridge
