version: '3.9'
services:
  db:
    image: postgres
    container_name: Operator_DB
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    expose:
      - 5432

  operator-lufthansa:
    container_name: operator-lufthansa
    build:
      context: .
    ports:
      - "8081:8081"
    links:
      - db

#  operator-tarom:
#    container_name: operator-tarom
#    build:
#      context: .
#    ports:
#      - "8383:8282"
#    links:
#      - tarom