name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  VERSION: latest

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: maven

    - name: Code vulnerability scanning
      uses: anchore/scan-action@v3
      id: scan
      with:
        path: "${{ github.workspace }}"
        fail-build: false
        severity-cutoff: high
        acs-report-enable: true

    - name: Upload vulnerability report
      uses: github/codeql-action/upload-sarif@v2
      if: success() || failure()
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}

    - name: Build, unit tests and integration tests - Admin
      working-directory: ./admin
      run: |
        chmod +x mvnw                                 
        ./mvnw clean install

    - name: Build, unit tests and integration tests - Booking
      working-directory: ./booking
      run: |
        chmod +x mvnw                                 
        ./mvnw clean install

    - name: Build, unit tests and integration tests - Flight-search
      working-directory: ./flight-search
      run: |
        chmod +x mvnw                                 
        ./mvnw clean install

    - name: Build, unit tests and integration tests - Notification
      working-directory: ./notification
      run: |
        chmod +x mvnw                                 
        ./mvnw clean install

    - name: Build, unit tests and integration tests - Operator
      working-directory: ./operator
      run: |
        chmod +x mvnw                                 
        ./mvnw clean install

    - name: Build, unit tests and integration tests - Payments
      working-directory: ./payments
      run: |
        chmod +x mvnw                                 
        ./mvnw clean install



